---
name: "TUIMDB"
guid: "ccc76c68-2d1e-44bc-b8f6-4760d6c6d5c2"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Provides metadata from tuimdb.com."
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "Metadata"
owner: "TUIMDB"
artifacts:
- "Jellyfin.Plugin.TUIMDB.dll"
changelog: >
  Initial release.
